name: Fetch laundry data

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: run script
        run: |
          python scrape.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "fetch data $(date '+%Y-%m-%d %H:%M')"
          git push
